# Hello World example for DTU biosustain and DTU bioengineering Data Club

name: Hello World example

on:
  push:

jobs:
  say-hello-world:
    runs-on: ubuntu-latest
    steps:
    - name: biosustain
      run: echo "Hello DTU biosustain!"
    - name: bioengineering
      run: echo "Hello DTU bioengineering!"
  cowjob: 
    runs-on: ubuntu-latest
    steps:
    - name: cowjob
      run: echo "job1!"
    - name: cowjob2
      run: echo "job2!"
      